databases:
  - name: warehouse
    plan: free
    databaseName: warehouse
    user: warehouseuser

services:
  - type: web
    plan: free
    name: warehouse
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn warehouse.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: warehouse
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4