# Generated by Django 5.0.1 on 2024-05-30 00:53

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('artist', 'Artist'), ('designer', 'Designer'), ('company', 'Company')], max_length=8)),
                ('name', models.CharField(max_length=150)),
                ('about', models.TextField(max_length=1000)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('poster', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=inventory.models.upload_to)),
                ('time', models.DateTimeField(blank=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('painting', 'Painting'), ('wallart', 'Wall Art'), ('prints', 'Prints'), ('objects', 'Objects'), ('goods', 'Goods')], max_length=9)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('materials_used', models.CharField(max_length=200)),
                ('creation_period', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=150)),
                ('listing_start', models.DateField(blank=True)),
                ('listing_end', models.DateField(blank=True)),
                ('current_price', models.IntegerField(default=0)),
                ('starting_price', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=inventory.models.upload_to)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='inventory.item')),
            ],
        ),
    ]
